[SERVICE]
    Flush       1
    Daemon      Off
    Log_Level   info
    Parsers_File parsers.conf

# -------------------------------------
# INPUTS
# --------------------------------------

[INPUT]
    Name    tail
    Tag     cowrie
    Path    /var/log/cowrie/cowrie.json
    Parser  json
    Mem_Buf_Limit       10MB
    Skip_Long_Lines     On
    Refresh_Interval    5

[INPUT]
    Name    tail
    Tag     canarytokens
    Path    /var/log/canarytokens/*.log
    Mem_Buf_Limit       5MB
    Skip_Long_Lines     On
    Refresh_Interval    5

[INPUT]
    Name    tail
    Tag     dcept
    Path    /var/log/dcept/dcept.log
    Mem_Buf_Limit       5MB
    Skip_Long_Lines     On
    Refresh_Interval    5


# -------------------------------------
# ENRICHMENT
# --------------------------------------


[FILTER]
    Name    modify
    Match   cowrie
    Set     source_type     cowrie
    Set     product         tripwyre
    Set     log_type        cowrie_alert

[FILTER]
    Name    modify
    Match   canarytokens
    Set     source_type     canarytoken
    Set     product         tripwyre
    Set     log_type        canary_alert

[FILTER]
    Name    modify
    Match   dcept
    Set     source_type     dcept
    Set     product         tripwyre
    Set     log_type        dcept_alert

#-------------------------------------
# FILTERING
#--------------------------------------

[FILTER]
    Name    grep
    Match   canarytokens
    Regex   log     ms-office|MSOffice

[FILTER]
    Name    grep
    Match   cowrie
    Regex   eventid     cowrie.session.connect|cowrie.login.success|cowrie.command.input|cowrie.session.closed

[FILTER]
    Name    grep
    Match   dcept
    Regex   log CRITICAL 

# -------------------------------------
# NORMALIZE MESSAGE FIELD FOR SYSLOG
# --------------------------------------

[FILTER]
    Name    modify
    Match   cowrie
    Hard_rename   message  syslog_message

[FILTER]
    Name    modify
    Match   dcept
    Hard_rename   log  syslog_message

[FILTER]
    Name    modify
    Match   canarytokens
    Hard_rename   log  syslog_message

# Adding a hostname/program marker for nicer syslog output

[FILTER]
    Name    modify
    Match   cowrie
    Set     syslog_hostname    tripwyre
    Set     syslog_appname     cowrie

[FILTER]
    Name    modify
    Match   dcept
    Set     syslog_hostname    tripwyre
    Set     syslog_appname     dcept

[FILTER]
    Name    modify
    Match   canarytokens
    Set     syslog_hostname    tripwyre
    Set     syslog_appname     canarytokens

# -------------------------------------
# Debug Outputs
# --------------------------------------

[OUTPUT]
    Name    stdout
    Match   *

# Keep the file outputs for debugging purposes, but they can be removed or commented out in production

[OUTPUT]
    Name    file
    Match   canarytokens
    Path    /fluent-bit/out
    File    canarytokens-processed.log

[OUTPUT]
    Name    file
    Match   cowrie
    Path    /fluent-bit/out
    File    cowrie-processed.log 

[OUTPUT]
    Name    file
    Match   dcept
    Path    /fluent-bit/out
    File    DCEPT-processed.log

# -------------------------------------
# SYSLOG OUTPUTS
# --------------------------------------

[OUTPUT]
    Name    syslog
    Match   cowrie
    Host    192.120.1.198
    Port    514
    Mode    udp
    Syslog_Format rfc5424
    Syslog_Hostname_Key syslog_hostname
    Syslog_Appname_Key syslog_appname
    Syslog_Message_Key syslog_message
    Syslog_Procid_Key session

[OUTPUT]
    Name    syslog
    Match   dcept
    Host    192.120.1.198
    Port    514
    Mode    udp
    Syslog_Format rfc5424
    Syslog_Hostname_Key syslog_hostname
    Syslog_Appname_Key syslog_appname
    Syslog_Message_Key syslog_message

[OUTPUT]
    Name    syslog
    Match   canarytokens
    Host    192.120.1.198
    Port    514
    Mode    udp
    Syslog_Format rfc5424
    Syslog_Hostname_Key syslog_hostname
    Syslog_Appname_Key syslog_appname
    Syslog_Message_Key syslog_message